### PR TITLE
Refactor `Spatial` trait and add tests for lerp()

### LINKED ISSUE #44: Reverse interpolation is incorrect for unsigned integers
The implementation of `lerp(a, b, w)` where the spatial type is unsigned and a > b is incorrect.

The following will fail as `lerp(...)` returns 15 instead of the expected 5:
```rust
assert_eq!(lerp(&10u32, &1, &0.5), 5);
```

I'm pretty sure this is because the implementation of `lerp` assumes `.sub()` can return a negative number. The implementation has to change to handle unsigned types correctly but the `Spatial` trait doesn't provide enough information to do that.

The solution I'm thinking of involves changing the `Spatial` trait to abstract linear interpolation itself, maybe with a rename:

```rust
pub trait Lerp {
    type Scalar;

    fn lerp(&self, other: &Self, weight: &Self::Scalar) -> Self where Self: Sized;
}
```

And then `lerp()` can change to be a trivial wrapper around this.

### PR DESCRIPTION
**Pull request by abonander**
closes #44

cc @bvssvni 

I'd recommend maybe adding a `.travis.yml` as well to run CI tests for this crate.

### CODE REVIEW

**Comment by abonander** [comment]
cc @zummenix

**Comment by abonander** [comment]
@bvssvni Looks like I have write permissions again but I'm sure you'd like to review before merging.

**Comment by bvssvni** [comment]
Looks good. Merge when ready.

**Comment by abonander** [comment]
@bvssvni since I added some tests, do you want me to add a Travis config as well so we can get CI on this crate?

**Comment by bvssvni** [comment]
Yes, that would be nice.

**Comment by abonander** [comment]
Added. That should be all that's really necessary if you just want to build and test on stable.

**Comment by bvssvni** [comment]
Merging.

**Comment by bvssvni** [comment]
Thanks!

**Comment by abonander** [comment]
Thanks for the quick publish!

**Pull request merged**
